{% set name = "lca_algebraic" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ./

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python 
    - pip
  host:
    - brightway2 >=2.3
    - bw2data >=3.6.2
    - ipython >=7.13.0
    - ipywidgets >=7.5.1
    - matplotlib >=3.1.1
    - nbconvert >=5.6.1
    - nbformat >=4.4.0
    - numpy >=1.16.6
    - pandas
    - python 
    - salib
    - scipy >=1.3.2
    - seaborn >=0.9.0
    - sympy >=1.5.1
    - tabulate >=0.8.6

test:
  imports:
    - lca_algebraic

about:
  home: "https://github.com/oie-mines-paristech/lca_algebraic/"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "This library provides a layer above brightway2 for defining parametric models and running super fast LCA for monte carlo analysis."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
