{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}
{% set summary = data.get('summary') %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  path: ../

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python 
    - pip
  run:
    - brightway2 >=2.3
    - bw2data >=3.6.2
    - ipython >=7.13.0
    - ipywidgets >=7.5.1
    - matplotlib >=3.1.1
    - nbconvert >=5.6.1
    - nbformat >=4.4.0
    - numpy >=1.16.6
    - python
    - pandas
    - salib
    - scipy >=1.3.2
    - seaborn >=0.9.0
    - sympy >=1.5.1
    - tabulate >=0.8.6

test:
  imports:
    - lca_algebraic

about:
  home: "https://github.com/oie-mines-paristech/lca_algebraic/"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: {{ summary }}
  description :
  doc_url: ""
  dev_url: ""


